//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace torque.Postgres.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DatabaseObjects {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DatabaseObjects() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("torque.Postgres.Resources.DatabaseObjects", typeof(DatabaseObjects).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with indexes as (
        ///    select
        ///        schemaname as schema,
        ///        tablename as table_name,
        ///        indexname as name,
        ///        indexdef as definition,
        ///        indexdef as create_statement
        ///    FROM
        ///        pg_indexes
        ///    order by
        ///        schemaname, tablename, indexname
        ///)
        ///select
        ///    nspname as Schema,
        ///    conname as Name,
        ///    relname as TableName,
        ///    pg_get_constraintdef(pg_constraint.oid) as Definition,
        ///    tc.constraint_type as Type
        ///from
        ///    pg_constraint
        ///    INNER JOIN pg_class
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Constraint {
            get {
                return ResourceManager.GetString("Constraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select
        ///	nspname as Schema,
        ///	proname as Name,
        ///	pg_get_functiondef(p.oid) as FullDefinition
        ///from pg_proc p
        ///INNER JOIN pg_namespace n
        ///  ON n.oid=p.pronamespace
        ///join information_schema.routines r
        ///  on r.routine_schema = n.nspname
        ///  and r.specific_name = p.proname || &apos;_&apos; || p.oid
        ///where p.prokind != &apos;a&apos;
        ///and nspname not in (&apos;pg_internal&apos;, &apos;pg_catalog&apos;, &apos;information_schema&apos;, &apos;pg_toast&apos;)
        ///and nspname not like &apos;pg_temp_%&apos; and nspname not like &apos;pg_toast_temp_%&apos;
        ///and pg_get_functiondef(p.oid) like &apos;%CREATE O [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Function {
            get {
                return ResourceManager.GetString("Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT n.nspname AS Schema,
        ///   c.relname AS TableName,
        ///   i.relname AS Name,
        ///   pg_get_indexdef(i.oid) AS Definition
        ///FROM pg_index x
        ///JOIN pg_class c ON c.oid = x.indrelid
        ///JOIN pg_class i ON i.oid = x.indexrelid
        ///LEFT JOIN pg_namespace n ON n.oid = c.relnamespace
        ///WHERE c.relkind in (&apos;r&apos;, &apos;m&apos;, &apos;p&apos;) AND i.relkind in (&apos;i&apos;, &apos;I&apos;)
        ///  and nspname not in (&apos;pg_catalog&apos;, &apos;information_schema&apos;, &apos;pg_toast&apos;)
        ///  and nspname not like &apos;pg_temp_%&apos; and nspname not like &apos;pg_toast_temp_%&apos;
        ///  and indisprimary = false
        ///orde [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select
        ///	nspname as Schema,
        ///	proname as Name,
        ///	pg_get_functiondef(p.oid) as FullDefinition
        ///from pg_proc p
        ///INNER JOIN pg_namespace n
        ///  ON n.oid=p.pronamespace
        ///join information_schema.routines r
        ///  on r.routine_schema = n.nspname
        ///  and r.specific_name = p.proname || &apos;_&apos; || p.oid
        ///where p.prokind != &apos;a&apos;
        ///and nspname not in (&apos;pg_internal&apos;, &apos;pg_catalog&apos;, &apos;information_schema&apos;, &apos;pg_toast&apos;)
        ///and nspname not like &apos;pg_temp_%&apos; and nspname not like &apos;pg_toast_temp_%&apos;
        ///and pg_get_functiondef(p.oid) like &apos;%CREATE O [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Procedure {
            get {
                return ResourceManager.GetString("Procedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select
        ///    nspname as SchemaName
        ///from
        ///    pg_catalog.pg_namespace
        ///where nspname not in (&apos;pg_internal&apos;, &apos;pg_catalog&apos;, &apos;information_schema&apos;, &apos;pg_toast&apos;) 
        ///     and nspname not like &apos;pg_temp_%&apos; and nspname not like &apos;pg_toast_temp_%&apos;
        ///order by 1;.
        /// </summary>
        public static string Schema {
            get {
                return ResourceManager.GetString("Schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with r as (
        ///    select
        ///        c.relname as name,
        ///        n.nspname as schema,
        ///        c.relkind as relationtype,
        ///        c.oid as oid,
        ///        case when c.relkind in (&apos;m&apos;, &apos;v&apos;) then
        ///          pg_get_viewdef(c.oid)
        ///        else null end
        ///          as definition,
        ///        (SELECT
        ///              &apos;&quot;&apos; || nmsp_parent.nspname || &apos;&quot;.&quot;&apos; || parent.relname || &apos;&quot;&apos; as parent
        ///          FROM pg_inherits
        ///              JOIN pg_class parent            ON pg_inherits.inhparent = parent.oid
        ///              JOIN pg_cl [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
    }
}
