variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

build:
    stage: build
    image: jhart0/dotnet_python_node
    script:
        - dotnet build .

test:
    stage: test
    image: jhart0/dotnet_python_node
    script:
        - dotnet test .

compose:
    stage: test
    image: jhart0/dind_aws
    services:
    - name: docker:19.03.12-dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
    script:
        - docker-compose build
        - docker-compose up -d
        - sleep 30
        - docker-compose down