build:
    stage: build
    image: jhart0/dotnet_python_node
    script:
        - dotnet build .

test:
    stage: test
    image: jhart0/dotnet_python_node
    script:
        - dotnet test .

compose:
    stage: test
    image: jhart0/dind_aws
    script:
        - docker-compose build
        - docker-compose up -d
        - sleep 30
        - docker-compose down