version: '3.1'

services:

  db1:
    image: postgres
    command: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin

  db2:
    image: postgres
    command: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin

  torque:
    build:
        context: .
        dockerfile: Dockerfile
    command: ["server=db1;database=postgres;user id=postgres;password=admin", "server=db2;database=postgres;user id=postgres;password=admin"]
    depends_on: 
      - db1
      - db2
