version: '3.1'

services:

  db1:
    image: postgres
    command: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - ./sample_data/source.sql:/docker-entrypoint-initdb.d/source.sql
    ports:
      - 5433:5432 

  db2:
    image: postgres
    command: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - ./sample_data/dest.sql:/docker-entrypoint-initdb.d/dest.sql   
    ports:
      - 5434:5432 

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  torque:
    build:
        context: .
        dockerfile: Dockerfile
    command: ["compare", "postgres", "server=db1;database=postgres;user id=postgres;password=admin", "server=db2;database=postgres;user id=postgres;password=admin"]
    depends_on: 
      - db1
      - db2
